# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run build

      - name: Copy dist to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.NIAGAHOSTER_IP }}
          username: ${{ secrets.NIAGAHOSTER_USERNAME }}
          password: ${{ secrets.NIAGAHOSTER_PASSWORD }}
          port: ${{ secrets.NIAGAHOSTER_PORT }}
          source: "dist/*"
          target: "public_html"
          strip_components: 1
          overwrite: true



    # - name : NPM Test file
    # - run: npm test
